spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.200.37:3306/wspay?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: root
    
  flyway:
    cleanDisabled: true 
    enabled: true
    locations: classpath:db/migration
    baselineOnMigrate: true
    baselineVersion: 1 
    outOfOrder: true
    
  redis:
     host: 127.0.0.1 # Redis服务器地址
     database: 0 # Redis数据库索引（默认为0）
     port: 6379 # Redis服务器连接端口
     password: null # Redis服务器连接密码（默认为空）
     jedis:
        pool:
           max-active: 8 # 连接池最大连接数（使用负值表示没有限制）
           max-wait: -1ms # 连接池最大阻塞等待时间（使用负值表示没有限制）
           max-idle: 8 # 连接池中的最大空闲连接
           min-idle: 0 # 连接池中的最小空闲连接
     timeout: 3000ms # 连接超时时间（毫秒）    
     
mybatis:
  mapper-locations:
    - classpath*:mapper/*.xml 
        
    